---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  # TODO: (engineering-services) Switch this back to policyfile_zero
  # when kitchen supports named run lists for suites.
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private

suites:
  - name: default
    excludes: [ 'macosx-10.10' ]
    run_list:
      - recipe[test]
      - recipe[test::repo]

  - name: local_package_install
    excludes: [ 'macosx-10.10' ]
    run_list:
      - recipe[test]
      - recipe[test::local]

  - name: chefdk
    run_list:
      - recipe[test::chefdk]

  - name: push_client
    # we don't yet have push client packages for trusty, only precise
    excludes: [ 'ubuntu-14.04', 'macosx-10.10' ]
    run_list:
      - recipe[test::push]
